theme = "autumn"

[editor]
line-number = "relative"
cursorline = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

#[editor.whitespace.render]
#space = "all"
#tab = "all"
#newline = "none"

#[editor.indent-guides]
#render = true
#character = "|"

[keys.insert]
"C-[" = "normal_mode"

[keys.normal]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
